name:                TreeHaskellAlt
version:             0.1.0.0
github:              "sanagif/TreeHaskellAlt"
license:             BSD3
author:              "sanagif"
maintainer:          "sanagif@vivaldi.net"
copyright:           "2020 sanagif"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TreeHaskellAlt#readme>

dependencies:
- base >= 4.7 && < 5
- argparser >= 0.3.4

library:
  source-dirs: src

executables:
  TreeHaskellAlt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TreeHaskellAlt

tests:
  TreeHaskellAlt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TreeHaskellAlt
